### ISSUE TITLE
NaN in int col

### ISSUE THREAD

**Issue by IvanStrazov** [ru-corporate/boo#18]
When loading a dataframe, a part of columns are set type np.int64. But they have NaN values. The problem is solved by replacing in boo/columns.py/class Column/method dtype: numpy.int64 -> numpy.float64. But it's bad decision for memory consumption.

**Comment by artemzz99** [comment]
Have a same ploblem

**Comment by epogrebnyak** [comment]
Great to get some feedback! To reiterate about column types:

We set column type here to distinguish between strings and and numeric columns:

https://github.com/ru-corporate/boo/blob/37ef476a27a53940fd854fd5f732cb2b2e052d45/boo/columns.py#L393-L395

The motivation for setting a type is to allow faster import here `dtype=NAMES` 
(when type is set, the import is hopefully fatser, also, minor reason INN is better as string than an integer, because it may start with zero):

https://github.com/ru-corporate/boo/blob/37ef476a27a53940fd854fd5f732cb2b2e052d45/boo/main.py#L62-L74

The raw data is in thousand rubles, so I chose `int`-linke type for numeric columns.

Now about NaNs - some columns are not filled for some companies, there may be a lot of data lacking for smaller companies, which do not provide cash flow form, for example. 

So `NaNs` are inherent to a dataset, maybe I need to leean more about why is this a problem with dtype? If we want to shut down `NaN`s we can later use `.dropna()` or `.fillna(0)` methods. 

Not sure why setting dtype `numpy.float64` may solve the problem, @IvanStrazov? The data omissions in origial dataset will stilll be there, does  `numpy.float64`  mask them differently than  `numpy.int64`?

**Comment by IvanStrazov** [comment]
@epogrebnyak 
Type `np.float64` allows storage `np.nan` and `np.inf`, but `np.int64` throws an exception. It's important for creating dataframe, before which we can't use `.dropna()` or `.fillna()`. When the built-in parser of `pd.read_csv()` with `dtype=None` examines the attribute values, it uses `np.float64` for features with `NaNs`

**Comment by epogrebnyak** [comment]
I see! Could also be a pandas version issue - will need a proper test on missing values. I'm able to geretae who;le dataset locally with `np.int64`, but will do a propertest next.

As of now I shut down `dtypes` in pandas read_csv() with 4578f46, as a temp fix. 

Are you installing from pip or here from repo?

**Comment by IvanStrazov** [comment]
From repo. 

Maybe it maybe good decision to download dataset with default `dtype`, detect `NaNs` and transform them to `-1` (that is a clearly wrong value). After can use `.astype()` for specific columns.

Or

Some strong way with pre-checking file. It'll more lingering variant, but with reduced memory.

**Comment by epogrebnyak** [comment]
In pandas 1.0 there is new NaN type, `pandas.NA`, replacing np.nan. pandas.NA is a fallback for missing integers. 

I think of putting integer dtype as an option with richer error message, that suggests using pandas 1.0.

**Comment by epogrebnyak** [comment]
Will use `pd.Int64Dtype()` - should work from version 0.24.0 and up.

https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html

**Comment by IvanStrazov** [comment]
Wow! This works really well. Thank you for your amazing library)

**Comment by epogrebnyak** [comment]
@IvanStrazov, @artemzz99 - thanks for drawing attention to a `NaN` issue, I'm glad we were able spot it and figure to use `pd.Int64Dtype()`. 

I was able to refresh the tests with c4ef3a9, we now have a specific test on treating the missing variables and it luckily passes in green:

https://travis-ci.com/github/ru-corporate/boo/builds/161969015

Please write back with any usecases or examples how you use `boo`. It is a bit frustrating to develop the library in the dark, I'm always happy to hear feedback about it :)

**Comment by IvanStrazov** [comment]
I merge boo with federal tax service data and predict number of employees over inn. I don’t have specific examples of `boo` now except loading dataframes. But if they appear in my future, I'll write to you about this)
